import { Token, FeedEvent, Narrative, Stats } from './types';

export const INITIAL_TOKENS: Token[] = [
  {
    id: 'pepe2',
    name: 'Pepe Reloaded',
    ticker: 'PEPE2',
    emoji: '🐸',
    color: '#00ff88',
    signal: 94,
    signalDelta: +18,
    tier: 'FIRE',
    risk: 'MED',
    socialVelocity: 4820,
    velocityDelta: +1240,
    marketCap: '$2.4M',
    priceChange24h: +147.3,
    narratives: ['Pepe revival', 'BNB native'],
    platforms: ['X', 'TG', 'Discord'],
    blipX: 62,
    blipY: 28,
    age: '3h',
    sparkline: [20, 25, 22, 30, 45, 52, 48, 61, 75, 88, 94],
  },
  {
    id: 'wojak99',
    name: 'Wojak 99',
    ticker: 'WJK99',
    emoji: '😢',
    color: '#00d4ff',
    signal: 81,
    signalDelta: +11,
    tier: 'HOT',
    risk: 'LOW',
    socialVelocity: 2930,
    velocityDelta: +640,
    marketCap: '$890K',
    priceChange24h: +63.1,
    narratives: ['Wojak meta', 'CT favorite'],
    platforms: ['X', 'TG'],
    blipX: 38,
    blipY: 55,
    age: '7h',
    sparkline: [40, 38, 44, 50, 55, 60, 58, 65, 72, 78, 81],
  },
  {
    id: 'doge3',
    name: 'DogeThree',
    ticker: 'DOGE3',
    emoji: '🐕',
    color: '#ffd60a',
    signal: 73,
    signalDelta: +6,
    tier: 'HOT',
    risk: 'LOW',
    socialVelocity: 1870,
    velocityDelta: +220,
    marketCap: '$5.1M',
    priceChange24h: +28.4,
    narratives: ['Dog coins', 'Classic revival'],
    platforms: ['X', 'Reddit', 'TG'],
    blipX: 71,
    blipY: 64,
    age: '1d',
    sparkline: [55, 58, 60, 62, 64, 68, 70, 69, 72, 72, 73],
  },
  {
    id: 'catgirl',
    name: 'CatGirl AI',
    ticker: 'CGAI',
    emoji: '😺',
    color: '#ff2d78',
    signal: 67,
    signalDelta: -4,
    tier: 'HOT',
    risk: 'HIGH',
    socialVelocity: 1420,
    velocityDelta: -180,
    marketCap: '$340K',
    priceChange24h: -12.7,
    narratives: ['AI + meme', 'Anime culture'],
    platforms: ['X', 'Discord'],
    blipX: 28,
    blipY: 35,
    age: '12h',
    sparkline: [80, 78, 76, 72, 70, 68, 71, 70, 68, 67, 67],
  },
  {
    id: 'bonk2',
    name: 'Bonk 2.0',
    ticker: 'BONK2',
    emoji: '🔨',
    color: '#ff8c00',
    signal: 58,
    signalDelta: +3,
    tier: 'WARM',
    risk: 'MED',
    socialVelocity: 980,
    velocityDelta: +60,
    marketCap: '$1.2M',
    priceChange24h: +8.9,
    narratives: ['BNB native', 'Community driven'],
    platforms: ['X', 'TG'],
    blipX: 55,
    blipY: 72,
    age: '2d',
    sparkline: [50, 52, 50, 53, 55, 54, 56, 57, 57, 58, 58],
  },
  {
    id: 'grok2',
    name: 'GrokMeme',
    ticker: 'GRKMM',
    emoji: '🤖',
    color: '#9945ff',
    signal: 45,
    signalDelta: +14,
    tier: 'WARM',
    risk: 'DEGEN',
    socialVelocity: 620,
    velocityDelta: +310,
    marketCap: '$88K',
    priceChange24h: +211.5,
    narratives: ['AI narrative', 'Grok hype'],
    platforms: ['X'],
    blipX: 45,
    blipY: 42,
    age: '45m',
    sparkline: [10, 11, 12, 13, 14, 18, 22, 28, 35, 40, 45],
  },
  {
    id: 'moon404',
    name: 'Moon404',
    ticker: 'M404',
    emoji: '🌕',
    color: '#c0c0c0',
    signal: 31,
    signalDelta: -9,
    tier: 'COLD',
    risk: 'HIGH',
    socialVelocity: 240,
    velocityDelta: -120,
    marketCap: '$65K',
    priceChange24h: -34.2,
    narratives: ['Fading hype'],
    platforms: ['TG'],
    blipX: 82,
    blipY: 45,
    age: '3d',
    sparkline: [60, 55, 52, 48, 44, 40, 38, 35, 33, 32, 31],
  },
  {
    id: 'based99',
    name: 'BasedPepe',
    ticker: 'BPEPE',
    emoji: '🫡',
    color: '#00ff88',
    signal: 88,
    signalDelta: +22,
    tier: 'FIRE',
    risk: 'MED',
    socialVelocity: 3640,
    velocityDelta: +1800,
    marketCap: '$450K',
    priceChange24h: +89.2,
    narratives: ['Based meta', 'Pepe branch'],
    platforms: ['X', 'TG', 'Discord'],
    blipX: 30,
    blipY: 72,
    age: '6h',
    sparkline: [15, 20, 25, 32, 42, 54, 62, 70, 78, 84, 88],
  },
];

export const INITIAL_NARRATIVES: Narrative[] = [
  { id: 'pepe-revival', label: 'Pepe Revival', score: 92, tokens: ['PEPE2', 'BPEPE'], growth: +34, color: '#00ff88' },
  { id: 'ai-meme', label: 'AI × Meme', score: 78, tokens: ['CGAI', 'GRKMM'], growth: +28, color: '#9945ff' },
  { id: 'dog-meta', label: 'Dog Meta', score: 71, tokens: ['DOGE3', 'BONK2'], growth: +12, color: '#ffd60a' },
  { id: 'wojak', label: 'Wojak Season', score: 65, tokens: ['WJK99'], growth: +19, color: '#00d4ff' },
  { id: 'bnb-native', label: 'BNB Native', score: 60, tokens: ['PEPE2', 'BONK2'], growth: +8, color: '#f0b90b' },
];

export const INITIAL_FEED: FeedEvent[] = [
  {
    id: 'f1', type: 'SIGNAL_UP', ticker: 'PEPE2', emoji: '🐸',
    message: 'Signal spiked +18 pts. CT volume exploding.',
    platform: 'X', timestamp: new Date(Date.now() - 120000), value: 94, color: '#00ff88',
  },
  {
    id: 'f2', type: 'NEW_TOKEN', ticker: 'GRKMM', emoji: '🤖',
    message: 'New token detected. Grok narrative, early entry.',
    platform: 'X', timestamp: new Date(Date.now() - 240000), value: 45, color: '#9945ff',
  },
  {
    id: 'f3', type: 'NARRATIVE', ticker: 'BPEPE', emoji: '🫡',
    message: '"Based Pepe" narrative forming. 3 tokens tracking.',
    platform: 'TG', timestamp: new Date(Date.now() - 360000), color: '#00ff88',
  },
  {
    id: 'f4', type: 'ALERT', ticker: 'M404', emoji: '🌕',
    message: 'Velocity dropping. Consider exit.',
    platform: 'TG', timestamp: new Date(Date.now() - 540000), color: '#ff2d78',
  },
  {
    id: 'f5', type: 'SIGNAL_UP', ticker: 'WJK99', emoji: '😢',
    message: 'Wojak memes trending on X. +640 mentions/hr.',
    platform: 'X', timestamp: new Date(Date.now() - 720000), value: 81, color: '#00d4ff',
  },
  {
    id: 'f6', type: 'SIGNAL_DOWN', ticker: 'CGAI', emoji: '😺',
    message: 'Social velocity cooling. -180 mentions/hr.',
    platform: 'X', timestamp: new Date(Date.now() - 900000), value: 67, color: '#ff2d78',
  },
  {
    id: 'f7', type: 'NARRATIVE', ticker: 'DOGE3', emoji: '🐕',
    message: 'Dog meta heating on Reddit. Historical pattern match.',
    platform: 'Reddit', timestamp: new Date(Date.now() - 1100000), color: '#ffd60a',
  },
];

export const INITIAL_STATS: Stats = {
  tokensScanned: 2847,
  activeSignals: 23,
  narrativesTracked: 8,
  alertsToday: 41,
};

export const TICKER_ITEMS = [
  { ticker: 'PEPE2', change: '+147.3%', color: '#00ff88' },
  { ticker: 'BPEPE', change: '+89.2%', color: '#00ff88' },
  { ticker: 'GRKMM', change: '+211.5%', color: '#9945ff' },
  { ticker: 'WJK99', change: '+63.1%', color: '#00d4ff' },
  { ticker: 'DOGE3', change: '+28.4%', color: '#ffd60a' },
  { ticker: 'BONK2', change: '+8.9%', color: '#ff8c00' },
  { ticker: 'CGAI', change: '-12.7%', color: '#ff2d78' },
  { ticker: 'M404', change: '-34.2%', color: '#ff2d78' },
];
